
name: wagg_application_ios
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.12
  webview_windows: ^0.0.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.7
  device_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/waggvet.jpg